# **Sorting & Ranking of Data**

In [78]:
# Import libraries
import pandas as pd
import numpy as np

In [79]:
# Load Retail sales data
df = pd.read_csv("../datasets/retail_sales.csv", 
                 parse_dates = ["Date"],
                 dtype = {"Category": "category", "Region": "category"})
df.head()

        Date     Category        Sales  Quantity      Profit Region
0 2023-01-01  Electronics  1149.014246      11.0  383.664245  North
1 2023-01-01     Clothing   958.520710       7.0  224.054049   East
2 2023-01-01   Home Goods  1473.763845       2.0  466.593090  South
3 2023-01-01       Sports  1230.230419       6.0  123.310460   West
4 2023-01-01         NaN?   828.585950      12.0   88.591355   East

In [80]:
# Make copy of original dataframe to avoid changing it
df1 = df.copy()

In [81]:
# Sorting Data by Quantity Sold in descending order and then by Sales in ascending order
df_sorted = df1.sort_values(by = ["Quantity", "Sales"], ascending = [False, True])
df_sorted.head(10)

           Date     Category       Sales  Quantity      Profit Region
312  2023-03-04   Home Goods    0.000000      19.0    0.000000   West
528  2023-04-16       Sports    0.000000      19.0  270.577388   West
1708 2023-12-08       Sports  227.942727      19.0   61.534381  North
571  2023-04-25     Clothing  361.006937      19.0   57.285585   West
1213 2023-08-31       Sports  368.305917      19.0   73.419555   West
118  2023-01-24       Sports  477.014426      19.0  158.914530  South
1244 2023-09-06        Books  487.544479      19.0  166.992986  North
1018 2023-07-23       Sports  497.954560      19.0   93.681572   West
890  2023-06-28  Electronics  524.205006      19.0  159.197678   West
1199 2023-08-28        Books  546.930926      19.0  157.349422  North

In [82]:
# Rank Salary within Group
df1["Sales_Rank"] = df1.groupby("Quantity")["Sales"].rank(method = "dense", ascending  = False)
df1.head()

,Date,Category,Sales,Quantity,Profit,Region,Sales_Rank
0,2023-01-01,Electronics,1149.014246,11.0,383.664245,North,29.0
1,2023-01-01,Clothing,958.520710,7.0,224.054049,East,56.0
2,2023-01-01,Home Goods,1473.763845,2.0,466.593090,South,7.0
3,2023-01-01,Sports,1230.230419,6.0,123.310460,West,24.0
4,2023-01-01,NaN?,828.585950,12.0,88.591355,East,68.0

## Part 1 — Sorting

In [83]:
# Make another copy of original dataframe to avoid changing it
df2 = df.copy()
df2.head()

        Date     Category        Sales  Quantity      Profit Region
0 2023-01-01  Electronics  1149.014246      11.0  383.664245  North
1 2023-01-01     Clothing   958.520710       7.0  224.054049   East
2 2023-01-01   Home Goods  1473.763845       2.0  466.593090  South
3 2023-01-01       Sports  1230.230419       6.0  123.310460   West
4 2023-01-01         NaN?   828.585950      12.0   88.591355   East

In [84]:
# Sort by Sales - lowest to highest
df_sorted_sales = df2.sort_values(by = ["Sales"], ascending = True).reset_index(drop = True)
df_sorted_sales.head()

        Date     Category  Sales  Quantity      Profit Region
0 2023-04-22        Books    0.0       6.0  315.088936  South
1 2023-04-17       Sports    0.0      11.0  378.225841  South
2 2023-04-16       Sports    0.0      19.0  270.577388   West
3 2023-04-16  Electronics    0.0       4.0  153.210888   West
4 2023-01-21   Home Goods    0.0       4.0  190.598776  North

In [85]:
# Sort by Sales - Highest to lowest
df_sorted_sales = df2.sort_values(by = ["Sales"], ascending = False).reset_index(drop = True)
df_sorted_sales.head()

        Date     Category        Sales  Quantity      Profit Region
0 2023-11-04       Sports  1888.932537       7.0  624.033248   East
1 2023-01-13        Books  1835.181414      17.0  207.524391   West
2 2023-08-18  Electronics  1829.793884       2.0  516.259116   West
3 2023-08-27  Electronics  1790.061382       5.0  184.641417  South
4 2023-02-28  Electronics  1779.311393      12.0  703.228418  South

In [86]:
# Sort by Quantity
df_sorted_qty = df2.sort_values(by = ["Quantity"], ascending = True).reset_index(drop = True)
df_sorted_qty.head()

        Date     Category        Sales  Quantity      Profit Region
0 2023-01-09  Electronics  1101.946289       0.0  136.923436   West
1 2023-12-29        Books  1257.545552       1.0  322.622384   West
2 2023-12-29       Sports   371.968313       1.0   93.302684  South
3 2023-01-11  Electronics   486.841126       1.0   62.281990   West
4 2023-01-11       Sports   746.015693       1.0  218.291274   East

In [87]:
# Display only Category, Sales and Quantity
df_sorted_qty[["Category", "Sales", "Quantity"]]

         Category        Sales  Quantity
0     Electronics  1101.946289       0.0
1           Books  1257.545552       1.0
2          Sports   371.968313       1.0
3     Electronics   486.841126       1.0
4          Sports   746.015693       1.0
...           ...          ...       ...
1820       Sports     0.000000       NaN
1821       Sports   625.000000       NaN
1822       Sports   993.435738       NaN
1823       Sports  1061.695040       NaN
1824       Sports  1533.677303       NaN

[1825 rows x 3 columns]

In [88]:
# Sort by Region → alphabetical order and Sales → highest to lowest
df_sorted_region_sales = df2.sort_values(by = ["Region", "Sales"], ascending = [True, False]).reset_index(drop = True)
df_sorted_region_sales.head()

        Date     Category        Sales  Quantity      Profit Region
0 2023-11-04       Sports  1888.932537       7.0  624.033248   East
1 2023-02-13       Sports  1733.725594      15.0  551.027710   East
2 2023-08-21     Clothing  1683.520596      11.0  189.351770   East
3 2023-12-19        Books  1683.125949      15.0  251.258952   East
4 2023-07-26  Electronics  1622.691263       8.0  443.590784   East

## Part 2 — Understanding groupby()

In [89]:
# Group by Category
df2.groupby("Category")

# "Divide my DataFrame into separate groups based on the unique values in the Category column."
#  It does not calculate anything yet. It only creates the groups.

In [90]:
# Total Sales by Category
df2.groupby("Category")["Sales"].sum()

Category
Books          370971.872558
Clothing       350981.822773
Electronics    364090.406288
Home Goods     347493.827088
NaN?              828.585950
Nan               823.190573
Null             1106.847949
Sports         346685.063298
Name: Sales, dtype: float64

In [91]:
# Total Sales by Category — Highest to Lowest
cat_sales = (
    df2.groupby("Category", as_index=False)["Sales"].sum().sort_values("Sales", ascending = False)
    )

# as_index=False → Keep Category as a normal column.

cat_sales

      Category          Sales
0        Books  370971.872558
2  Electronics  364090.406288
1     Clothing  350981.822773
3   Home Goods  347493.827088
7       Sports  346685.063298
6         Null    1106.847949
4         NaN?     828.585950
5          Nan     823.190573

In [92]:
# Average Sales by Region
sales_region = df2.groupby("Region", 
                           as_index = False)["Sales"].mean().sort_values(by = ["Sales"],
                                                                         ascending  = False)
sales_region

  Region        Sales
1    Nan  1716.710787
0   East   991.036812
4   West   986.403291
2  North   976.677632
3  South   969.981985

In [93]:
# Total Sales by Region
total_sale_region = df2.groupby("Region")["Sales"].sum()
total_sale_region

Region
East     393441.614509
Nan        1716.710787
North    448295.032930
South    469471.280583
West     470514.369828
Name: Sales, dtype: float64

### Exercise 8 — Total Profit by Region

In [94]:
# Calculate total Profit for each Region
profit_region = df2.groupby("Region", 
                            as_index=False)["Profit"].sum().sort_values(by = "Profit",
                                                                        ascending=False)
profit_region

  Region         Profit
4   West  122517.775250
3  South  118036.969923
2  North  112126.470662
0   East   98973.620400
1    Nan     545.617726

### Exercise 9 — Multiple Statistics

In [95]:
# For each Category, calculate: Total Sales, Average Sales, Total Profit, Average Profit
cat_stats = df2.groupby("Category").agg(
    Total_Sales = ("Sales", "sum"),
    Average_Sales = ("Sales", "mean"),
    Total_profit = ("Profit", "sum"),
    Average_profit = ("Profit", "mean")
).reset_index()

cat_stats

      Category    Total_Sales  Average_Sales  Total_profit  Average_profit
0        Books  370971.872558    1019.153496  92304.452141      253.583660
1     Clothing  350981.822773     961.594035  90082.119920      246.800329
2  Electronics  364090.406288    1011.362240  90439.697795      250.525479
3   Home Goods  347493.827088     954.653371  87447.820056      240.241264
4         NaN?     828.585950     828.585950     88.591355       88.591355
5          Nan     823.190573     823.190573    253.433301      253.433301
6         Null    1106.847949    1106.847949    381.784578      381.784578
7       Sports  346685.063298     955.055271  92065.220851      252.926431

# Part 3 — Basic Ranking
### Exercise 10 — Rank All Sales

In [96]:
# Rank all Sales values from highest to lowest
df2["Sales_Rank"] = df2["Sales"].rank(ascending = False)
df2.head()

,Date,Category,Sales,Quantity,Profit,Region,Sales_Rank
0,2023-01-01,Electronics,1149.014246,11.0,383.664245,North,587.0
1,2023-01-01,Clothing,958.520710,7.0,224.054049,East,1001.0
2,2023-01-01,Home Goods,1473.763845,2.0,466.593090,South,112.0
3,2023-01-01,Sports,1230.230419,6.0,123.310460,West,416.0
4,2023-01-01,NaN?,828.585950,12.0,88.591355,East,1280.0

### Exercise 11 — Display Top Ranked Sales

In [97]:
df2[["Date", "Category", "Sales", "Sales_Rank"]].sort_values(by = 
                                                             ["Sales_Rank"]).reset_index(drop = True)

           Date     Category        Sales  Sales_Rank
0    2023-11-04       Sports  1888.932537         1.0
1    2023-01-13        Books  1835.181414         2.0
2    2023-08-18  Electronics  1829.793884         3.0
3    2023-08-27  Electronics  1790.061382         4.0
4    2023-02-28  Electronics  1779.311393         5.0
...         ...          ...          ...         ...
1820 2023-03-25  Electronics     0.000000      1801.0
1821 2023-03-23   Home Goods     0.000000      1801.0
1822 2023-03-22     Clothing     0.000000      1801.0
1823 2023-01-10  Electronics          NaN         NaN
1824 2023-01-31       Sports          NaN         NaN

[1825 rows x 4 columns]

### Exercise 12 — Rank Profit

In [98]:
# Create Rank_profit col and highest profit receives Rank 1
df2["Rank_Profit"] = df2["Profit"].rank(ascending=False)
df2.head()

,Date,Category,Sales,Quantity,Profit,Region,Sales_Rank,Rank_Profit
0,2023-01-01,Electronics,1149.014246,11.0,383.664245,North,587.0,257.0
1,2023-01-01,Clothing,958.520710,7.0,224.054049,East,1001.0,948.0
2,2023-01-01,Home Goods,1473.763845,2.0,466.593090,South,112.0,93.0
3,2023-01-01,Sports,1230.230419,6.0,123.310460,West,416.0,1588.0
4,2023-01-01,NaN?,828.585950,12.0,88.591355,East,1280.0,1739.0

In [99]:
# Highest profit receives Rank 1
df2[["Category", "Sales", "Profit", "Rank_Profit"]].sort_values(
    by = ["Rank_Profit"], ascending=True).reset_index(drop=True)

         Category        Sales      Profit  Rank_Profit
0     Electronics  1779.311393  703.228418          1.0
1           Books  1643.510926  652.843041          2.0
2        Clothing  1763.100369  649.168113          3.0
3           Books  1655.733944  645.714161          4.0
4     Electronics  1637.930677  636.877412          5.0
...           ...          ...         ...          ...
1820     Clothing   136.162932   20.802643       1821.0
1821     Clothing    70.098843    9.795696       1822.0
1822     Clothing    43.656557    8.140877       1823.0
1823   Home Goods     0.000000    0.000000       1824.5
1824  Electronics     0.000000    0.000000       1824.5

[1825 rows x 4 columns]

# Part 4 — GroupBy + Ranking
### Exercise 13 — Rank Sales Within Category

In [100]:
# Rank within each category
df2["Category_Sales_Rank"] = (df2.groupby("Category")["Sales"].rank(ascending=False))
cat_sales_rank = df2.sort_values(by = ["Category", "Category_Sales_Rank"]).reset_index(drop = True)
cat_sales_rank.head()

,Date,Category,Sales,Quantity,Profit,Region,Sales_Rank,Rank_Profit,Category_Sales_Rank
0,2023-01-13,Books,1835.181414,17.0,207.524391,West,2.0,1062.0,1.0
1,2023-02-04,Books,1771.997486,2.0,473.695116,West,6.0,83.0,2.0
2,2023-12-19,Books,1683.125949,15.0,251.258952,East,19.0,798.0,3.0
3,2023-05-01,Books,1659.857989,14.0,274.761198,North,22.0,675.0,4.0
4,2023-10-25,Books,1655.733944,7.0,645.714161,North,23.0,4.0,5.0

### Exercise 14 — Rank Sales Within Region

In [101]:
# Rank within each region
df2["Region_Sales_Rank"] = df2.groupby("Region")["Sales"].rank(ascending=False)
df3 = df2[["Date", "Category", "Sales", "Region", "Region_Sales_Rank"]]
region_sales_rank = df3.sort_values(by = ["Region", "Region_Sales_Rank"]).reset_index(drop = True)
region_sales_rank.head()

        Date     Category        Sales Region  Region_Sales_Rank
0 2023-11-04       Sports  1888.932537   East                1.0
1 2023-02-13       Sports  1733.725594   East                2.0
2 2023-08-21     Clothing  1683.520596   East                3.0
3 2023-12-19        Books  1683.125949   East                4.0
4 2023-07-26  Electronics  1622.691263   East                5.0

### Exercise 15 — Rank Profit Within Category

In [102]:
# Category proft rank
df2["Category_Profit_Rank"] = df2.groupby("Category")["Profit"].rank(ascending=False)
# Required cols
df4 = df2[["Date", "Category", "Sales", "Profit", "Category_Profit_Rank"]]
# Sort Values
df4_sorted = df4.sort_values(by = ["Category","Category_Profit_Rank"]).reset_index(drop = True)

In [103]:
# display result
df4_sorted

           Date Category        Sales      Profit  Category_Profit_Rank
0    2023-12-13    Books  1643.510926  652.843041                   1.0
1    2023-10-25    Books  1655.733944  645.714161                   2.0
2    2023-12-23    Books  1522.712825  588.264825                   3.0
3    2023-12-27    Books  1404.515912  553.699994                   4.0
4    2023-06-03    Books  1395.087651  548.537823                   5.0
...         ...      ...          ...         ...                   ...
1820 2023-11-21   Sports   148.748068   21.368432                 364.0
1821 2023-01-03      NaN  1246.763474  283.696992                   NaN
1822 2023-01-04      NaN   839.000000  102.610251                   NaN
1823 2023-01-04      NaN  1142.812776  237.179042                   NaN
1824 2023-01-19      NaN  1209.727715  183.830902                   NaN

[1825 rows x 5 columns]

# Part 5 — Advanced Challenge

### Exercise 16 - Find the top 3 categories by Sales within each Region

In [104]:
# Copy of Original dataset
df5 = df.copy()
# Calculate Total Sales for each Category within each Region
region_cat_sale = df5.groupby(["Region", "Category"], as_index=False)["Sales"].sum()

In [105]:
# Rank Sales within each Region
region_cat_sale["Sales_Rank"] = (region_cat_sale.groupby("Region")["Sales"].rank(ascending = False))

In [106]:
# Keep only the Top 3
top_3_by_region = region_cat_sale[
    region_cat_sale["Sales_Rank"] <=3].sort_values(by = ["Region", "Sales_Rank"]).reset_index(drop = True)

In [107]:
top_3_by_region

   Region     Category          Sales  Sales_Rank
0    East   Home Goods   83753.251154         1.0
1    East       Sports   81103.933608         2.0
2    East        Books   80136.652469         3.0
3     Nan  Electronics    1716.710787         1.0
4   North     Clothing  100478.577422         1.0
5   North        Books   98238.877170         2.0
6   North       Sports   84088.295869         3.0
7   South  Electronics   98288.505974         1.0
8   South     Clothing   97609.451099         2.0
9   South        Books   97286.478229         3.0
10   West  Electronics  102932.805985         1.0
11   West       Sports  100670.635797         2.0
12   West        Books   95309.864690         3.0

### Exercise 17 — Category-level Sales and Profit Statistics
### For each Category, find:
- Total Sales
- Average Sales
- Maximum Sales
- Total Profit
- Number of transactions

    - Then sort the result by Total Sales from highest to lowest.

In [108]:
cat_summery = df5.groupby("Category", as_index = False).agg(
    Total_Sales = ("Sales", "sum"),
    Average_Sales = ("Sales", "mean"),
    Maximum_Sales = ("Sales", "max"),
    Total_Profit = ("Profit", "sum"),
    Transactions = ("Sales", "count")
).sort_values(by = ["Total_Sales"], ascending=False)

In [109]:
# display result
cat_summery

,Category,Total_Sales,Average_Sales,Maximum_Sales,Total_Profit,Transactions
0,Books,370971.872558,1019.153496,1835.181414,92304.452141,364
2,Electronics,364090.406288,1011.362240,1829.793884,90439.697795,360
1,Clothing,350981.822773,961.594035,1763.100369,90082.119920,365
3,Home Goods,347493.827088,954.653371,1739.263732,87447.820056,364
7,Sports,346685.063298,955.055271,1888.932537,92065.220851,363
6,Null,1106.847949,1106.847949,1106.847949,381.784578,1
4,NaN?,828.585950,828.585950,828.585950,88.591355,1
5,Nan,823.190573,823.190573,823.190573,253.433301,1