# **Merging and Joining DataFrames**

## 1. merge()  →  Match rows using a key
### Methods:
- INNER → only matching
- LEFT  → everything from left
- RIGHT → everything from right
- OUTER → everything from both
## 2. concat()  →  Stack records

In [1]:
# Import Library
import pandas as pd

In [8]:
# Sample DataFrames
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 5],
    "Name": ["Usman", "Ali", "Abbas", "Khan"]
})
# Orders Dataframe
orders = pd.DataFrame({
    "Order_ID": [101, 102, 103, 104],
    "Customer_ID": [1, 2, 2, 6],
    "Amount": [240, 300, 500, 100]
})

# 1. Inner Merge

In [10]:
# Inner merge on customer id (only matching)
df_inner = pd.merge(customers, orders, on = "Customer_ID", how = "inner")
df_inner

   Customer_ID   Name  Order_ID  Amount
0            1  Usman       101     240
1            2    Ali       102     300
2            2    Ali       103     500

# 2. Left Merge

In [11]:
# Left Merge (everythig from left)
df_left = pd.merge(customers, orders, on = "Customer_ID", how = "left")
df_left

   Customer_ID   Name  Order_ID  Amount
0            1  Usman     101.0   240.0
1            2    Ali     102.0   300.0
2            2    Ali     103.0   500.0
3            3  Abbas       NaN     NaN
4            5   Khan       NaN     NaN

# 3. Right Merge

In [12]:
# Right Merge (everything from right)
df_right = pd.merge(customers, orders, on = "Customer_ID", how = "right") 
df_right

   Customer_ID   Name  Order_ID  Amount
0            1  Usman       101     240
1            2    Ali       102     300
2            2    Ali       103     500
3            6    NaN       104     100

# 2. Concate()

In [17]:
# Concatenate Rows
df_concat = pd.concat([customers, orders])
df_concat

   Customer_ID   Name  Order_ID  Amount
0            1  Usman       NaN     NaN
1            2    Ali       NaN     NaN
2            3  Abbas       NaN     NaN
3            5   Khan       NaN     NaN
0            1    NaN     101.0   240.0
1            2    NaN     102.0   300.0
2            2    NaN     103.0   500.0
3            6    NaN     104.0   100.0

## 3. join() — combine using the index

In [20]:
# Combine dataframes using index
sales = pd.DataFrame({
    "Sales": [500, 1000, 2000]},
    index = [101, 102, 103]
)
# region dataframe
region = pd.DataFrame({
    "Region": ["North", "South", "East"]},
                      index = [101,102,103])

In [23]:
# Join DataFrames using index
result = region.join(sales)
result

    Region  Sales
101  North    500
102  South   1000
103   East   2000