# **Applying Functions: apply, map & pipe**

- All used to apply operations to data
- `map()`   → transform individual values
- `apply()` → apply a function to rows or columns
- `pipe()`  → pass the entire DataFrame through functions

### 1. map() — transform individual values

In [91]:
# Load pandas library and dataset
import pandas as pd
# Load Dataset
df = pd.read_csv("../datasets/retail_sales.csv", parse_dates = ["Date"])
df.head()

        Date     Category        Sales  Quantity      Profit Region
0 2023-01-01  Electronics  1149.014246      11.0  383.664245  North
1 2023-01-01     Clothing   958.520710       7.0  224.054049   East
2 2023-01-01   Home Goods  1473.763845       2.0  466.593090  South
3 2023-01-01       Sports  1230.230419       6.0  123.310460   West
4 2023-01-01         NaN?   828.585950      12.0   88.591355   East

In [92]:
# map region cols
df["Region_Name"] = df["Region"].map({
    "North": "N",
    "East": "E",
    "South": "S",
    "West": "W",
    "nan": "not",
    "Nan": "Na"
    })
df.head()

,Date,Category,Sales,Quantity,Profit,Region,Region_Name
0,2023-01-01,Electronics,1149.014246,11.0,383.664245,North,N
1,2023-01-01,Clothing,958.520710,7.0,224.054049,East,E
2,2023-01-01,Home Goods,1473.763845,2.0,466.593090,South,S
3,2023-01-01,Sports,1230.230419,6.0,123.310460,West,W
4,2023-01-01,NaN?,828.585950,12.0,88.591355,East,E

In [93]:
# Total region_name count
df.groupby("Region_Name").size()

Region_Name
E     398
N     460
Na      1
S     484
W     477
dtype: int64

# 2. apply() — apply a function to rows or columns

In [94]:
# Multiply sale col by 2 (same as map function)
df["Sales"].apply(lambda x : x * 2)

0       2298.028492
1       1917.041419
2       2947.527689
3       2460.460837
4       1657.171901
           ...
1820    2265.498008
1821    1358.523941
1822    2387.467456
1823    2152.237412
1824    1407.946886
Name: Sales, Length: 1825, dtype: float64

In [95]:
# Same as apply function
df["Sales"].map(lambda x: x*2)

0       2298.028492
1       1917.041419
2       2947.527689
3       2460.460837
4       1657.171901
           ...
1820    2265.498008
1821    1358.523941
1822    2387.467456
1823    2152.237412
1824    1407.946886
Name: Sales, Length: 1825, dtype: float64

In [96]:
# rounded Sales col values upto 2 decimals
df["Sales"].apply(lambda x: round(x, 2))

0       1149.01
1        958.52
2       1473.76
3       1230.23
4        828.59
         ...
1820    1132.75
1821     679.26
1822    1193.73
1823    1076.12
1824     703.97
Name: Sales, Length: 1825, dtype: float64

In [97]:
# Remove sales values with 0 values
df = df[df["Sales"] > 0].reset_index(drop = True)

In [103]:
# Apply to a row: This is where apply() becomes especially useful
# Calculate profit margin
df["Profit_Margin"] = df.apply(lambda row : row["Profit"] / row["Sales"], axis = 1)
df["Profit_Margin"] = df["Profit_Margin"].apply(lambda x : x*100)