# **Applying Functions: apply, map & pipe**

- All used to apply operations to data
- `map()`   → transform individual values
- `apply()` → apply a function to rows or columns
- `pipe()`  → pass the entire DataFrame through functions

### 1. map() — transform individual values

In [53]:
# Load pandas library and dataset
import pandas as pd
# Load Dataset
df = pd.read_csv("../datasets/retail_sales.csv", parse_dates = ["Date"])
df.head()

        Date     Category        Sales  Quantity      Profit Region
0 2023-01-01  Electronics  1149.014246      11.0  383.664245  North
1 2023-01-01     Clothing   958.520710       7.0  224.054049   East
2 2023-01-01   Home Goods  1473.763845       2.0  466.593090  South
3 2023-01-01       Sports  1230.230419       6.0  123.310460   West
4 2023-01-01         NaN?   828.585950      12.0   88.591355   East

In [54]:
# map region cols
df["Region_Name"] = df["Region"].map({
    "North": "N",
    "East": "E",
    "South": "S",
    "West": "W",
    "nan": "not",
    "Nan": "Na"
    })
df.head()

,Date,Category,Sales,Quantity,Profit,Region,Region_Name
0,2023-01-01,Electronics,1149.014246,11.0,383.664245,North,N
1,2023-01-01,Clothing,958.520710,7.0,224.054049,East,E
2,2023-01-01,Home Goods,1473.763845,2.0,466.593090,South,S
3,2023-01-01,Sports,1230.230419,6.0,123.310460,West,W
4,2023-01-01,NaN?,828.585950,12.0,88.591355,East,E

In [55]:
# Total region_name count
df.groupby("Region_Name").size()

Region_Name
E     398
N     460
Na      1
S     484
W     477
dtype: int64

# 2. apply() — apply a function to rows or columns

In [56]:
# Multiply sale col by 2 (same as map function)
df["Sales"].apply(lambda x : x * 2)

0       2298.028492
1       1917.041419
2       2947.527689
3       2460.460837
4       1657.171901
           ...
1820    2265.498008
1821    1358.523941
1822    2387.467456
1823    2152.237412
1824    1407.946886
Name: Sales, Length: 1825, dtype: float64

In [57]:
# Same as apply function
df["Sales"].map(lambda x: x*2)

0       2298.028492
1       1917.041419
2       2947.527689
3       2460.460837
4       1657.171901
           ...
1820    2265.498008
1821    1358.523941
1822    2387.467456
1823    2152.237412
1824    1407.946886
Name: Sales, Length: 1825, dtype: float64

In [58]:
# rounded Sales col values upto 2 decimals
df["Sales"].apply(lambda x: round(x, 2))

0       1149.01
1        958.52
2       1473.76
3       1230.23
4        828.59
         ...
1820    1132.75
1821     679.26
1822    1193.73
1823    1076.12
1824     703.97
Name: Sales, Length: 1825, dtype: float64

In [59]:
# Remove sales values with 0 values
df = df[df["Sales"] > 0].reset_index(drop = True)

In [60]:
# Apply to a row: This is where apply() becomes especially useful
# Calculate profit margin
df["Profit_Margin"] = df.apply(lambda row : row["Profit"] / row["Sales"], axis = 1)
df["Profit_Margin"] = df["Profit_Margin"].apply(lambda x : x*100)

In [61]:
df.describe()

,Date,Sales,Quantity,Profit,Profit_Margin
count,1778,1778.000000,1774.000000,1778.000000,1778.000000
mean,2023-07-04 20:58:34.960630,1005.298043,10.086809,248.011008,24.750885
min,2023-01-01 00:00:00,43.656557,0.000000,8.140877,10.006811
25%,2023-04-06 00:00:00,803.063642,5.000000,156.475566,17.052471
50%,2023-07-07 00:00:00,1006.430438,10.000000,228.057049,24.653589
75%,2023-10-03 18:00:00,1212.460579,15.000000,322.496737,32.467868
max,2023-12-31 00:00:00,1888.932537,19.000000,703.228418,39.995477
std,NaN,302.185312,5.510009,117.773310,8.801989

In [62]:
# Sales Category based on Sales
def Sales_Category (row):
    if row["Sales"] >= 1500:
        return "High"
    elif row["Sales"] >= 1000:
        return "Medium"
    else:
        return "Low"
df["Sales_Category"] = df.apply(Sales_Category, axis = 1)
df.head()

,Date,Category,Sales,Quantity,Profit,Region,Region_Name,Profit_Margin,Sales_Category
0,2023-01-01,Electronics,1149.014246,11.0,383.664245,North,N,33.390730,Medium
1,2023-01-01,Clothing,958.520710,7.0,224.054049,East,E,23.374983,Low
2,2023-01-01,Home Goods,1473.763845,2.0,466.593090,South,S,31.659963,Medium
3,2023-01-01,Sports,1230.230419,6.0,123.310460,West,W,10.023363,Medium
4,2023-01-01,NaN?,828.585950,12.0,88.591355,East,E,10.691873,Low

In [63]:
# Count Values
df["Sales_Category"].value_counts()

Sales_Category
Low       873
Medium    809
High       96
Name: count, dtype: int64

# 3. pipe() — passes the whole dataframe to a function

In [64]:
# pipe() - method chaining
def add_revenue(df):
    df["Revenue"] = df["Profit"]*0.20
    return df
def add_net_revenue(df):
    df["Net_Revenue"] = df["Revenue"] - df["Profit"]
    return df
# pipe
df = (df
      .pipe(add_revenue)
      .pipe(add_net_revenue)
      )

In [65]:
# display dataset
df.head()

,Date,Category,Sales,Quantity,Profit,Region,Region_Name,Profit_Margin,Sales_Category,Revenue,Net_Revenue
0,2023-01-01,Electronics,1149.014246,11.0,383.664245,North,N,33.390730,Medium,76.732849,-306.931396
1,2023-01-01,Clothing,958.520710,7.0,224.054049,East,E,23.374983,Low,44.810810,-179.243239
2,2023-01-01,Home Goods,1473.763845,2.0,466.593090,South,S,31.659963,Medium,93.318618,-373.274472
3,2023-01-01,Sports,1230.230419,6.0,123.310460,West,W,10.023363,Medium,24.662092,-98.648368
4,2023-01-01,NaN?,828.585950,12.0,88.591355,East,E,10.691873,Low,17.718271,-70.873084